#' Clean CSO data from wide to long format
#'
#' @description
#' Transforms wide-format CSO (Central Statistics Office) data into a tidy long
#' format. Converts date columns to proper date format and standardizes column
#' names.
#'
#' @param data Raw CSO data frame with statistics in wide format
#' @param value_name Name for the value column in the output
#'
#' @return A cleaned tibble with columns: date, statistic, nace_group, and the
#' specified value column
#'
#' @importFrom dplyr as_tibble rename_with rename mutate select everything
#' @importFrom tidyr pivot_longer
#' @importFrom stringr str_to_lower str_replace_all
#' @importFrom lubridate ym
#' @importFrom rlang :=
#'
#' @examples
#' \dontrun{
#' # Clean retail sales data
#' retail_data <- csodata::cso_get_data("RSM08")
#' clean_retail <- clean_cso_data(retail_data, "sales_index")
#'
#' # Clean online turnover data
#' online_data <- csodata::cso_get_data("RSM07")
#' clean_online <- clean_cso_data(online_data, "turnover_pct")
#' }
#'
#' @seealso \code{\link{get_retail_sales_index}},
#' \code{\link{get_online_turnover}}
#' @export
clean_cso_data <- function(data, value_name) {
  if (!is.data.frame(data) || ncol(data) < 3) {
    stop(
      paste0("Input data must be a data frame with at least 3 columns (2 ID ",
             "columns and >=1 time/value column) for pivoting.")
    )
  }

  # Use rlang to capture the desired name for later checks
  value_name_quo <- rlang::enquo(value_name)
  value_name_str <- rlang::as_name(value_name_quo)

  cleaned_data <- data |>
    dplyr::as_tibble() |>
    # 1. Pivot
    tidyr::pivot_longer(
      cols = -c(1, 2),
      names_to = "year_month",
      values_to = "value"
    ) |>
    # 2. Combine column name cleaning: Lowercase and replace dots.
    dplyr::rename_with(
      ~ .x |>
        stringr::str_to_lower() |>
        stringr::str_replace_all("\\.", "_"),
      dplyr::everything()
    ) |>
    # 3. Rename by the stable name "value"
    dplyr::rename({{value_name}} := value) |>
    # 4. Create date column
    dplyr::mutate(
      date = lubridate::ym(year_month)
    )

  # --- 5. POST-CLEANING CHECK: Validate expected ID/Value columns exist ---
  required_cols <- c("date", "statistic", "nace_group", value_name_str)
  missing_cols <- setdiff(required_cols, names(cleaned_data))

  if (length(missing_cols) > 0) {
    stop(
      paste0("Structural change detected in CSO table. The following critical ",
             "columns are missing after cleaning: "),
      paste(missing_cols, collapse = ", "),
      ". Check the raw CSO data structure."
    )
  }

  # 6. Final select and reorder
  cleaned_data |>
    dplyr::select(date, statistic, nace_group, {{value_name}})
}

#' Get retail sales index data
#'
#' @description
#' Retrieves and cleans Irish retail sales index data from CSO dataset RSM08.
#' Returns data in tidy long format with monthly observations by NACE group.
#'
#' @return A cleaned tibble with columns: date, statistic, nace_group,
#' observation
#'
#' @importFrom csodata cso_get_data
#'
#' @examples
#' \dontrun{
#' retail_sales <- get_retail_sales_index()
#' head(retail_sales)
#' }
#'
#' @seealso \code{\link{clean_cso_data}}
#' @export
get_retail_sales_index <- function() {
  retail_sales_index_raw_tbl <- csodata::cso_get_data("RSM08")
  clean_cso_data(retail_sales_index_raw_tbl, "observation")
}

#' Get online turnover data
#'
#' @description
#' Retrieves and cleans Irish online retail turnover data from CSO dataset
#' RSM07.
#' Returns percentage of turnover generated by online sales by NACE group.
#'
#' @return A cleaned tibble with columns: date, statistic, nace_group,
#' online_turnover_pct
#'
#' @importFrom csodata cso_get_data
#'
#' @examples
#' \dontrun{
#' online_turnover <- get_online_turnover()
#' head(online_turnover)
#' }
#'
#' @seealso \code{\link{clean_cso_data}}
#' @export
get_online_turnover <- function() {
  online_turnover_raw_tbl <- csodata::cso_get_data("RSM07")
  clean_cso_data(online_turnover_raw_tbl, "online_turnover_pct")
}

#' Get combined retail sales and online turnover data
#'
#' @description
#' Combines retail sales index data with online turnover percentages by matching
#' on date and NACE group. Provides a comprehensive view of retail performance
#' including online component.
#'
#' @return A merged tibble with retail sales index and online turnover data
#'
#' @importFrom dplyr left_join select
#'
#' @examples
#' \dontrun{
#' combined_data <- get_retail_sales_with_online()
#' head(combined_data)
#' }
#'
#' @seealso \code{\link{get_retail_sales_index}},
#' \code{\link{get_online_turnover}}
#' @export
get_retail_sales_with_online <- function() {
  retail_sales_index_tbl <- get_retail_sales_index()
  online_turnover_tbl <- get_online_turnover()

  retail_sales_index_tbl |>
    dplyr::left_join(
      online_turnover_tbl |> dplyr::select(-statistic),
      by = c("date", "nace_group")
    )
}
